packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@parcel/watcher': true
  electron: true
  esbuild: true
  puppeteer: true

minimumReleaseAgeExclude:
  - '@dev-centr/mermaid-svg-css-vars@0.1.2'
  - '@dev-centr/themed-svg@0.1.1'
