/**
 * Writes WinGet manifest fragments next to downloaded release binaries.
 * Usage: VERSION=0.3.0 ASSETS_DIR=release-assets node scripts/render-winget.mjs
 */
import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const version = (process.env.VERSION ?? '').replace(/^v/, '')
const root = process.env.ASSETS_DIR ?? 'release-assets'
const outDir = join(root, 'winget-manifests')

if (!version) {
  console.error('Set VERSION (e.g. 0.3.0 or v0.3.0)')
  process.exit(1)
}

const owner = 'AMDphreak'
const repo = 'nikon-camera-bridge'
const tag = `v${version}`
const base = `https://github.com/${owner}/${repo}/releases/download/${tag}`

async function sha256File(abs) {
  const buf = await readFile(abs)
  return createHash('sha256').update(buf).digest('hex').toUpperCase()
}

function archFromWinName(name) {
  if (name.includes('-arm64-')) return 'arm64'
  if (name.includes('-x64-')) return 'x64'
  return null
}

const files = await readdir(root)
const prefix = 'Webcam.Bridge.for.Nikon'

const msiRows = []
for (const name of files.filter((f) => f.endsWith('.msi') && f.startsWith(prefix) && f.includes('-win-'))) {
  const abs = join(root, name)
  const hash = await sha256File(abs)
  const arch = archFromWinName(name)
  if (!arch) continue
  msiRows.push({
    Architecture: arch,
    InstallerUrl: `${base}/${name}`,
    InstallerSha256: hash
  })
}

const zipRows = []
for (const name of files.filter((f) => f.endsWith('.zip') && f.startsWith(prefix) && f.includes('-win-'))) {
  const abs = join(root, name)
  const hash = await sha256File(abs)
  const arch = archFromWinName(name)
  if (!arch) continue
  zipRows.push({
    Architecture: arch,
    InstallerUrl: `${base}/${name}`,
    InstallerSha256: hash,
    NestedInstallerType: 'portable',
    NestedInstallerFiles: [{ RelativeFilePath: 'Webcam Bridge for Nikon.exe' }]
  })
}

const msixRows = []
for (const name of files.filter((f) => f.endsWith('.msix') && f.startsWith(prefix) && f.includes('-win-'))) {
  const abs = join(root, name)
  const hash = await sha256File(abs)
  const arch = archFromWinName(name)
  if (!arch) continue
  msixRows.push({
    Architecture: arch,
    InstallerUrl: `${base}/${name}`,
    InstallerSha256: hash
  })
}

const installers = [...msiRows, ...msixRows, ...zipRows].sort((a, b) =>
  `${a.Architecture}-${a.InstallerUrl}`.localeCompare(`${b.Architecture}-${b.InstallerUrl}`)
)

function installerYamlBlock(i) {
  if ('NestedInstallerType' in i) {
    return `  - Architecture: ${i.Architecture}
    InstallerType: zip
    InstallerUrl: ${i.InstallerUrl}
    InstallerSha256: ${i.InstallerSha256}
    NestedInstallerType: ${i.NestedInstallerType}
    NestedInstallerFiles:
      - RelativeFilePath: ${i.NestedInstallerFiles[0].RelativeFilePath}`
  }
  const ext = i.InstallerUrl.endsWith('.msix') ? 'msix' : 'msi'
  return `  - Architecture: ${i.Architecture}
    InstallerType: ${ext}
    InstallerUrl: ${i.InstallerUrl}
    InstallerSha256: ${i.InstallerSha256}`
}

if (installers.length === 0) {
  console.warn('No Windows .msi, .msix, or portable .zip installers found; writing WinGet README stub only.')
  await mkdir(outDir, { recursive: true })
  await writeFile(
    join(outDir, 'README.txt'),
    'No Windows .msi, .msix, or .zip artifacts were present when this manifest was generated.\n'
  )
} else {
  await mkdir(outDir, { recursive: true })

  const packageId = 'AMDphreak.WebcamBridgeforNikon'

  const installerYaml = `# Generated by scripts/render-winget.mjs — PR to https://github.com/microsoft/winget-pkgs
PackageIdentifier: ${packageId}
PackageVersion: ${version}
MinimumOSVersion: 10.0.17763.0
InstallerLocale: en-US
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Installers:
${installers.map((i) => installerYamlBlock(i)).join('\n')}
ManifestType: installer
ManifestVersion: 1.6.0
`

  const localeYaml = `# Generated by scripts/render-winget.mjs
PackageIdentifier: ${packageId}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: AMDphreak
PublisherUrl: https://github.com/${owner}
PackageName: Webcam Bridge for Nikon
PackageUrl: https://github.com/${owner}/${repo}
License: MIT
LicenseUrl: https://github.com/${owner}/${repo}/raw/main/LICENSE
ShortDescription: Nikon USB bridge shell (virtual camera + control API roadmap)
Moniker: webcam-bridge-for-nikon
Tags:
  - nikon
  - camera
  - webcam
  - bridge
ReleaseNotesUrl: https://github.com/${owner}/${repo}/releases/tag/${tag}
ManifestType: defaultLocale
ManifestVersion: 1.6.0
`

  const versionYaml = `# Generated by scripts/render-winget.mjs
PackageIdentifier: ${packageId}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
`

  await writeFile(join(outDir, `${packageId}.installer.yaml`), installerYaml)
  await writeFile(join(outDir, `${packageId}.locale.en-US.yaml`), localeYaml)
  await writeFile(join(outDir, `${packageId}.yaml`), versionYaml)

  console.log('WinGet manifests written to', outDir)
}
